
kind: pipeline
name: java8

platform:
  arch: amd64

steps:
- name: prepare-dependencies
  image: omz-ci-tools
  pull: never
  commands:
  - artifact-dl-java mvncentral/org.json:json:20210307

- name: prepare-source
  image: omz-ci-tools
  pull: never
  commands:
  - mkdir build
  - setversion util/main/java/org/omegazero/common/OmzLib.java
  - curl -G "https://omegazero.org/site/software/r/license_bin_full.php" --data-urlencode "srcurl=$DRONE_REPO_LINK/src/commit/$DRONE_COMMIT" > LICENSE_BIN

- name: build-util
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/util/META-INF
  - cp LICENSE_BIN build/util/META-INF/LICENSE
  - make util BINDIR=build
  depends_on:
  - prepare-dependencies
  - prepare-source

- name: build-config
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/config/META-INF
  - cp LICENSE_BIN build/config/META-INF/LICENSE
  - make config BINDIR=build
  depends_on:
  - prepare-dependencies
  - prepare-source

- name: build-events
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/events/META-INF
  - cp LICENSE_BIN build/events/META-INF/LICENSE
  - make events BINDIR=build
  depends_on:
  - prepare-dependencies
  - prepare-source
  - build-util

- name: build-logging
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/logging/META-INF
  - cp LICENSE_BIN build/logging/META-INF/LICENSE
  - make logging BINDIR=build
  depends_on:
  - prepare-dependencies
  - prepare-source
  - build-util
  - build-events

- name: build-all
  image: o-jvm-build
  pull: never
  commands:
  - mkdir -p build/omz-java-lib-all/META-INF
  - cp LICENSE_BIN build/omz-java-lib-all/META-INF/LICENSE
  - make alljar BINDIR=build
  depends_on:
  - build-util
  - build-config
  - build-events
  - build-logging

- name: publish
  image: omz-ci-tools
  pull: never
  commands:
  - artifact-push-java build/omz-java-lib-all.jar omz/org.omegazero.common:omz-common
  - artifact-push-java build/util.jar omz/org.omegazero.common:omz-common-util
  - artifact-push-java build/config.jar omz/org.omegazero.common:omz-common-config
  - artifact-push-java build/events.jar omz/org.omegazero.common:omz-common-events
  - artifact-push-java build/logging.jar omz/org.omegazero.common:omz-common-logging
  depends_on:
  - build-all
  environment:
    OMZ_ARTIFACT_PUSH_TOKEN:
      from_secret: artifact_push_token
